version: '3.9'
services:
  web:
    image: tmfev/gics:latest
    container_name: gics
    restart: always
    ports:
      - ${APP_PORT}:8080
    networks:
      - default
    volumes:
      - data:/var/gics

networks:
  default:
    name: docker_gics_network
    driver: bridge

volumes:
  data:
    name: docker_gics_data
    driver: local
